### ISSUE TITLE
Idea: Script to bulk download all documents

### ISSUE THREAD

**Issue by wngr** [grindsa/dkb-robo#16]
It would be great to have add the ability to actually download the documents per category in the DKB post box; and then having this as a standalone example.

Let me know what you think, I might then try to contribute something like that.

**Comment by grindsa** [comment]
I like the idea. Let me think about it a bid more in detail.

**Comment by wngr** [comment]
I toyed around a little bit: https://github.com/wngr/dkb-robo/commit/39e5ad752dd3770a826b1c18f9390c6f7c71a100

Unfortunately, I'm not sure how either the DKB website nor MechanicalSoup works:
```
2020-03-30 23:45:38.738584: DKBRobo.get_document_links(https://www.dkb.de/banking/postfach/ordner?$event=gotoFolder&folderNameOrId=%24inbox)

current url https://www.dkb.de/banking/postfach/ordner?$event=gotoFolder&folderNameOrId=%24inbox
trying to download https://www.dkb.de/DkbTransactionBanking/content/mailbox/MessageList.xhtml?$event=getMailboxAttachment&filename=Informationsbogen+zur+Einlagensicherung&row=0
2020-03-30 23:45:39.375502: DKBRobo.logout()

Traceback (most recent call last):
  File "dkb_download.py", line 33, in <module>
    POSTBOX_DIC = dkb.scan_postbox()
  File "/home/ow/src/dkb-downloads/dkb-robo/doc/dkb_robo/dkb_robo.py", line 783, in scan_postbox
    self.dkb_br.download_link(doc, f'./output/{link_name}/{name}.pdf')
  File "/home/ow/.local/lib/python3.7/site-packages/mechanicalsoup/stateful_browser.py", line 351, in download_link
    link = self._find_link_internal(link, args, kwargs)
  File "/home/ow/.local/lib/python3.7/site-packages/mechanicalsoup/stateful_browser.py", line 304, in _find_link_internal
    return self.find_link(*args, **kwargs)
  File "/home/ow/.local/lib/python3.7/site-packages/mechanicalsoup/stateful_browser.py", line 278, in find_link
    raise LinkNotFoundError()
mechanicalsoup.utils.LinkNotFoundError
```

Seems that this is returning a 404. You have any pointers for me?

**Comment by grindsa** [comment]
The looked into it yesterday. The document download from DKB Postbox has been designed in a strange way. Seems the links are not unique. Documents to download will be identified by the row number and the folder you are in. Anyway I pushed [an extension]( https://github.com/grindsa/dkb-robo/commit/b19e29691963eb49bd78e01467a824629003d0e0) to the devel branch. You have to specify the path to store the files when calling the scan_postbox method.  Give it a try and check if it works for you.

**Comment by wngr** [comment]
Thanks! The extension works for me.

I added support for pagination in https://github.com/wngr/dkb-robo/commit/4806b3fbbfa9d418f8e4978abea33d884f6b2e51
Should I open a PR with ^, or do you want to handle this another way?

**Comment by grindsa** [comment]
Just send a pull request.

Any proposal what do with the documents in the postbox after download? Delete, archive or should it be rather configurable?

**Comment by wngr** [comment]
I think it should be configurable, given that the Archive is limited at 50 MB.
OTOH, I would just rely on the DKB provided retention policies and let them take care of it – so it might be sufficient to just mark the downloaded docs as read (that is currently not the case).

**Comment by grindsa** [comment]
Thx I merged the PR. I also did a couple of smaller changes:
- downloaded documents will be marked as read after successful download
- by default scan_postbox() will only download unread documents. There is a ```download_all``` parameter (True/False) which can be used to download all documents. So something like
```
> document_dic = dkb.scan_postbox(path, download_all)
```

**Comment by wngr** [comment]
Awesome! Thanks for the swift actions.

I will give it a shot, and report back.

**Comment by grindsa** [comment]
implemented with v0.10

**Comment by wngr** [comment]
Reopening, as there seems to be an issue with the downloading:

Just checked out https://github.com/grindsa/dkb-robo/commit/e8a1fec9e6efec428178fedd76d1e4a2a2f99303:
```
➜  doc git:(devel) ✗ ./dkb_docdownload.py tmp                                                                                                                                                                                                                                                                            <<<
2020-04-30 21:21:06.660356: DKBRobo.login()

2020-04-30 21:21:06.660390: DKBRobo.new_instance()

2020-04-30 21:21:09.054640: DKBRobo.login_confirm()

check your banking app and confirm login...
2020-04-30 21:21:09.100812: poll(id: 1588267269057 status: WAITING

2020-04-30 21:21:11.148656: poll(id: 1588267269058 status: WAITING

2020-04-30 21:21:13.209655: poll(id: 1588267269059 status: WAITING

2020-04-30 21:21:15.258953: poll(id: 1588267269060 status: WAITING

2020-04-30 21:21:17.302965: poll(id: 1588267269061 status: WAITING

2020-04-30 21:21:19.350069: poll(id: 1588267269062 status: MAP_TO_EXIT

2020-04-30 21:21:19.350153: session got confirmed...

2020-04-30 21:21:22.319257: DKBRobo.get_financial_statement()

2020-04-30 21:21:23.102489: DKBRobo.parse_overview()

30.04.2020, 20:34 Uhr
Writing documents to tmp
2020-04-30 21:21:23.110294: DKBRobo.scan_postbox()

2020-04-30 21:21:23.598008: DKBRobo.get_document_links(https://www.dkb.de/banking/postfach/ordner?$event=gotoFolder&folderNameOrId=%24inbox)

2020-04-30 21:21:24.242838: DKBRobo.get_document_links(https://www.dkb.de/banking/postfach/ordner?$event=gotoFolder&folderNameOrId=%24vertragsinformationen)

2020-04-30 21:21:24.959083: DKBRobo.get_document(https://www.dkb.de/DkbTransactionBanking/content/mailbox/MessageList.xhtml?$event=getMailboxAttachment&filename=%C3%84nderungen+von+Vertragsbedingungen+zum+13.+September+2019&row=2)

2020-04-30 21:21:24.959130: create directory tmp/Vertragsinformationen

2020-04-30 21:21:29.169032: writing to tmp/Vertragsinformationen/%c3%84nderungen_von_Vertragsbedingungen_zum_13._September_2019.pdf

2020-04-30 21:21:29.169546: DKBRobo.update_downloadstate(Vertragsinformationen, https://www.dkb.de/DkbTransactionBanking/content/mailbox/MessageList.xhtml?$event=getMailboxAttachment&filename=%C3%84nderungen+von+Vertragsbedingungen+zum+13.+September+2019&row=2)

2020-04-30 21:21:29.169974: DKBRobo.logout()

Traceback (most recent call last):
  File "./dkb_docdownload.py", line 35, in <module>
    POSTBOX_DIC = dkb.scan_postbox(PATH)
  File "/home/ow/src/dkb-downloads/dkb-robo/doc/dkb_robo/dkb_robo.py", line 833, in scan_postbox
    pb_dic[link_name]['documents'] = self.get_document_links(pb_dic[link_name]['details'], path, link_name, download_all)
  File "/home/ow/src/dkb-downloads/dkb-robo/doc/dkb_robo/dkb_robo.py", line 204, in get_document_links
    self.update_downloadstate(link_name, self.base_url + link['href'])
  File "/home/ow/src/dkb-downloads/dkb-robo/doc/dkb_robo/dkb_robo.py", line 855, in update_downloadstate
    mark_link = link.lower()
NameError: name 'link' is not defined
```

**Comment by wngr** [comment]
Seems https://github.com/grindsa/dkb-robo/commit/0bff5630f4e3bcdb9f83e6f5294f6f4cec7e405e is the issue for me. Trying with https://github.com/grindsa/dkb-robo/commit/2845479096845efc14217e75af306d1af609725b works for me.

**Comment by grindsa** [comment]
Thx for spotting this. Stupig mistage form my side [14ba22c](https://github.com/grindsa/dkb-robo/commit/14ba22c79ed09b629a4b812c799b286537073e08) contains a fix...
