### ISSUE TITLE
Legacy login retired

### ISSUE THREAD

**Issue by angelo-peronio** [grindsa/dkb-robo#58]
The old DKB [frontend](https://www.ib.dkb.de/banking) has been retired, so attempting to login with `legacy_login` is not possible anymore.

In particular, one gets:

```text
legacy.Wrapper.login()

legacy.Wrapper._new_instance()

legacy.Wrapper._new_instance() ended

Starting new HTTPS connection (1): www.ib.dkb.de:443
https://www.ib.dkb.de:443 "GET /banking HTTP/11" 200 None
Traceback (most recent call last):
  File "C:\venvs\accounting\Lib\site-packages\dkb_robo\legacy.py", line 824, in login
    self.dkb_br["j_username"] = str(self.dkb_user)
    ~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\venvs\accounting\Lib\site-packages\mechanicalsoup\stateful_browser.py", line 122, in __setitem__
    self.form[name] = value
    ~~~~~~~~~^^^^^^
  File "C:\venvs\accounting\Lib\site-packages\mechanicalsoup\form.py", line 242, in __setitem__
    return self.set(name, value)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\accounting\Lib\site-packages\mechanicalsoup\form.py", line 283, in set
    raise LinkNotFoundError("No valid element named " + name)
mechanicalsoup.utils.LinkNotFoundError: No valid element named j_username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\venvs\accounting\Scripts\fetch.exe\__main__.py", line 7, in <module>
  File "C:\Users\angel\Documents\doc-Angelo\euri\accounting\src\accounting\dkb\fetch.py", line 171, in main
    with DKBRobo(
  File "C:\venvs\accounting\Lib\site-packages\dkb_robo\dkb_robo.py", line 54, in __enter__
    (self.account_dic, self.last_login) = self.wrapper.login()
                                          ^^^^^^^^^^^^^^^^^^^^
  File "C:\venvs\accounting\Lib\site-packages\dkb_robo\legacy.py", line 860, in login
    raise DKBRoboError('Login failed: LinkNotFoundError') from err
dkb_robo.legacy.DKBRoboError: Login failed: LinkNotFoundError
```

Should the support for the old frontend be dropped?

**Comment by grindsa** [comment]
Already saw it yesterday as well.

**Comment by grindsa** [comment]
Legacy frontend got disabled in [dkb-rob v0.27](https://github.com/grindsa/dkb-robo/releases/tag/0.27) and will be fully removed in one of the upcomfing releases.
