### ISSUE TITLE
Mile&More Credit card breaks dkb-robo

### ISSUE THREAD

**Issue by wonko21** [grindsa/dkb-robo#7]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wonko/git/wonko/dkb2influx/src/dkb2influx.py", line 15, in <module>
    transactions = dkb.get_transactions(account['transactions'], account['type'], date.today(), date(2017, 1, 1))
  File "/home/wonko/git/github/dkb-robo/dkb_robo/dkb_robo.py", line 373, in get_transactions
    transaction_list = self.get_creditcard_transactions(transaction_url, date_from, date_to)
  File "/home/wonko/git/github/dkb-robo/dkb_robo/dkb_robo.py", line 115, in get_creditcard_transactions
    self.dkb_br.select_form('#form1579108072_1')
  File "/usr/lib64/python3.6/site-packages/mechanicalsoup/stateful_browser.py", line 207, in select_form
    raise LinkNotFoundError()
mechanicalsoup.utils.LinkNotFoundError

**Comment by wonko21** [comment]
the mm card works a bit differen than the visa card. a new window is opened for the transactions with the m&m look

**Comment by grindsa** [comment]
Hi, Works still fine here.... Btw. DKB introduced additional html attributes last week making the checks for credit-card transactions failing. Fix is included in the latest commit or v.0.7.3

**Comment by grindsa** [comment]
Sorry. closed the wrong thread.  I unfortuately do not have a mm card,  but I could try to extend DKBRobo if you send me some html captures. Would that be an option?
